# 参考文档: doc/server_structure.md
# 开发环境依赖配置（包含测试工具）
name: ganghaofan-server-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - duckdb==0.10.3
    - pydantic==2.5.0
    - python-jose[cryptography]==3.3.0
    - python-multipart==0.0.6
    - httpx==0.25.0
    # 开发工具
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.10.1
    - flake8==6.1.0